DROP TABLE IF EXISTS lootItemGroupNames;

CREATE TABLE IF NOT EXISTS lootItemGroupNames(
lootGroupID INT(11) PRIMARY KEY AUTO_INCREMENT,
lootGroupName TEXT,
parentGroupID INT(11),
parentGroupName TEXT
);

INSERT INTO lootItemGroupNames (lootGroupID, lootGroupName, parentGroupID, parentGroupName) VALUES
(1, 'Small Energy Weapon', 53, 'Energy Weapon'),
(2, 'Medium Energy Weapon', 53, 'Energy Weapon'),
(3, 'Large Energy Weapon', 53, 'Energy Weapon'),
(4, 'Small Hybrid Weapon', 74, 'Hybrid Weapon'),
(5, 'Medium Hybrid Weapon', 74, 'Hybrid Weapon'),
(6, 'Large Hybrid Weapon', 74, 'Hybrid Weapon'),
(7, 'Small Projectile Weapon', 55, 'Projectile Weapon'),
(8, 'Medium Projectile Weapon', 55, 'Projectile Weapon'),
(9, 'Large Projectile Weapon', 55, 'Projectile Weapon'),
(10, 'Rocket Launcher', 507, 'Missile Launcher Rocket'),
(11, 'Light Missile Launcher', 509, 'Missile Launcher Light'),
(12, 'Rapid Light Missile Launcher', 511, 'Missile Launcher Rapid Light'),
(13, 'Heavy Missile Launcher', 510, 'Missile Launcher Heavy'),
(14, 'Heavy Assault Missile Launcher', 771, 'Missile Launcher Heavy Assault'),
(15, 'Cruise Missile Launcher', 506, 'Missile Launcher Cruise'),
(16, 'Torpedo Launcher', 508, 'Missile Launcher Torpedo'),
(17, 'Micro Shield Extender', 38, 'Shield Extender'),
(18, 'Small Shield Extender', 38, 'Shield Extender'),
(19, 'Medium Shield Extender', 38, 'Shield Extender'),
(20, 'Large Shield Extender', 38, 'Shield Extender'),
(21, 'Small Shield Booster', 40, 'Shield Booster'),
(22, 'Medium Shield Booster', 40, 'Shield Booster'),
(23, 'Large Shield Booster', 40, 'Shield Booster'),
(24, 'X-Large Shield Booster', 40, 'Shield Booster'),
(25, 'Small Hull Repairer', 63, 'Hull Repair Unit'),
(26, 'Medium Hull Repairer', 63, 'Hull Repair Unit'),
(27, 'Large Hull Repairer', 63, 'Hull Repair Unit'),
(28, 'Small Armor Repairer', 62, 'Armor Repair Unit'),
(29, 'Medium Armor Repairer', 62, 'Armor Repair Unit'),
(30, 'Large Armor Repairer', 62, 'Armor Repair Unit'),
(31, 'Small Armor Plate', 329, 'Armor Reinforcer'),
(32, 'Medium Armor Plate', 329, 'Armor Reinforcer'),
(33, 'Large Armor Plate', 329, 'Armor Reinforcer'),
# Faction turrets section
(34, 'True Sansha Small Energy Weapon', 53, 'Energy Weapon'),
(35, 'Dark Blood Small Energy Weapon', 53, 'Energy Weapon'),
(36, 'True Sansha Medium Energy Weapon', 53, 'Energy Weapon'),
(37, 'Dark Blood Medium Energy Weapon', 53, 'Energy Weapon'),
(38, 'True Sansha Large Energy Weapon', 53, 'Energy Weapon'),
(39, 'Dark Blood Large Energy Weapon', 53, 'Energy Weapon'),
(40, 'Dread Guristas Small Hybrid Weapon', 74, 'Hybrid Weapon'),
(41, 'Shadow Serpentis Small Hybrid Weapon', 74, 'Hybrid Weapon'),
(42, 'Dread Guristas Medium Hybrid Weapon', 74, 'Hybrid Weapon'),
(43, 'Shadow Serpentis Medium Hybrid Weapon', 74, 'Hybrid Weapon'),
(44, 'Dread Guristas Large Hybrid Weapon', 74, 'Hybrid Weapon'),
(45, 'Shadow Serpentis Large Hybrid Weapon', 74, 'Hybrid Weapon'),
(46, 'Domination Small Projectile Weapon', 55, 'Projectile Weapon'),
(47, 'Domination Medium Projectile Weapon', 55, 'Projectile Weapon'),
(48, 'Domination Large Projectile Weapon', 55, 'Projectile Weapon'),
# Faction modules section
(49, 'Domination Small Shield Booster', 40, 'Shield Booster'),
(50, 'Domination Medium Shield Booster', 40, 'Shield Booster'),
(51, 'Domination Large Shield Booster', 40, 'Shield Booster'),
(52, 'Domination X-Large Shield Booster', 40, 'Shield Booster'),
(53, 'Dread Guristas Small Shield Booster', 40, 'Shield Booster'),
(54, 'Dread Guristas Medium Shield Booster', 40, 'Shield Booster'),
(55, 'Dread Guristas Large Shield Booster', 40, 'Shield Booster'),
(56, 'Dread Guristas X-Large Shield Booster', 40, 'Shield Booster'),
(57, 'Domination Small Armor Repairer', 62, 'Armor Repair Unit'),
(58, 'Domination Medium Armor Repairer', 62, 'Armor Repair Unit'),
(59, 'Domination Large Armor Repairer', 62, 'Armor Repair Unit'),
(60, 'Shadow Serpentis Small Armor Repairer', 62, 'Armor Repair Unit'),
(61, 'Shadow Serpentis Medium Armor Repairer', 62, 'Armor Repair Unit'),
(62, 'Shadow Serpentis Large Armor Repairer', 62, 'Armor Repair Unit'),
(63, 'True Sansha Small Armor Repairer', 62, 'Armor Repair Unit'),
(64, 'True Sansha Medium Armor Repairer', 62, 'Armor Repair Unit'),
(65, 'True Sansha Large Armor Repairer', 62, 'Armor Repair Unit'),
(66, 'Dark Blood Small Armor Repairer', 62, 'Armor Repair Unit'),
(67, 'Dark Blood Medium Armor Repairer', 62, 'Armor Repair Unit'),
(68, 'Dark Blood Large Armor Repairer', 62, 'Armor Repair Unit'),
(69, 'Domination Rocket Launcher', 507, 'Missile Launcher Rocket'),
(70, 'True Sansha Rocket Launcher', 507, 'Missile Launcher Rocket'),
(71, 'Dread Guristas Rocket Launcher', 507, 'Missile Launcher Rocket'),
(72, 'Domination Light Missile Launcher', 509, 'Missile Launcher Light'),
(73, 'True Sansha Light Missile Launcher', 509, 'Missile Launcher Light'),
(74, 'Dread Guristas Light Missile Launcher', 509, 'Missile Launcher Light'),
(75, 'Domination Rapid Light Missile Launcher', 511, 'Missile Launcher Rapid Light'),
(76, 'True Sansha Rapid Light Missile Launcher', 511, 'Missile Launcher Rapid Light'),
(77, 'Dread Guristas Rapid Light Missile Launcher', 511, 'Missile Launcher Rapid Light'),
(78, 'Domination Heavy Missile Launcher', 510, 'Missile Launcher Heavy'),
(79, 'True Sansha Heavy Missile Launcher', 510, 'Missile Launcher Heavy'),
(80, 'Dread Guristas Heavy Missile Launcher', 510, 'Missile Launcher Heavy'),
(81, 'Domination Cruise Missile Launcher', 506, 'Missile Launcher Cruise'),
(82, 'True Sansha Cruise Missile Launcher', 506, 'Missile Launcher Cruise'),
(83, 'Dread Guristas Cruise Missile Launcher', 506, 'Missile Launcher Cruise'),
(84, 'Domination Torpedo Launcher', 508, 'Missile Launcher Torpedo'),
(85, 'True Sansha Torpedo Launcher', 508, 'Missile Launcher Torpedo'),
(86, 'Dread Guristas Torpedo Launcher', 508, 'Missile Launcher Torpedo'),
# Regular ammunition section
(87, 'Small Projectile Ammo', 83, 'Projectile Ammo'),
(88, 'Medium Projectile Ammo', 83, 'Projectile Ammo'),
(89, 'Large Projectile Ammo', 83, 'Projectile Ammo'),
(90, 'Small Hybrid Ammo', 85, 'Hybrid Ammo'),
(91, 'Medium Hybrid Ammo', 85, 'Hybrid Ammo'),
(92, 'Large Hybrid Ammo', 85, 'Hybrid Ammo'),
(93, 'Small Frequency Crystal', 86, 'Frequency Crystal'),
(94, 'Medium Frequency Crystal', 86, 'Frequency Crystal'),
(95, 'Large Frequency Crystal', 86, 'Frequency Crystal'),
(96, 'Rocket', 387, 'Rocket'),
(97, 'Light Missile', 384, 'Light Missile'),
(98, 'Heavy Missile', 385, 'Heavy Missile'),
(99, 'Heavy Assault Missile', 772, 'Assault Missile'),
(100, 'Cruise Missile', 386, 'Cruise Missile'),
(101, 'Torpedo', 89, 'Torpedo'),
# Faction ammunition section
(102, 'Angel Small Projectile Ammo', 83, 'Projectile Ammo'),
(103, 'Angel Medium Projectile Ammo', 83, 'Projectile Ammo'),
(104, 'Angel Large Projectile Ammo', 83, 'Projectile Ammo'),
(105, 'Serpentis Small Hybrid Ammo', 85, 'Hybrid Ammo'),
(106, 'Serpentis Medium Hybrid Ammo', 85, 'Hybrid Ammo'),
(107, 'Serpentis Large Hybrid Ammo', 85, 'Hybrid Ammo'),
(108, 'Guristas Small Hybrid Ammo', 85, 'Hybrid Ammo'),
(109, 'Guristas Medium Hybrid Ammo', 85, 'Hybrid Ammo'),
(110, 'Guristas Large Hybrid Ammo', 85, 'Hybrid Ammo'),
(111, 'Sansha Small Frequency Crystal', 86, 'Frequency Crystal'),
(112, 'Sansha Medium Frequency Crystal', 86, 'Frequency Crystal'),
(113, 'Sansha Large Frequency Crystal', 86, 'Frequency Crystal'),
(114, 'Blood Raiders Small Frequency Crystal', 86, 'Frequency Crystal'),
(115, 'Blood Raiders Medium Frequency Crystal', 86, 'Frequency Crystal'),
(116, 'Blood Raiders Large Frequency Crystal', 86, 'Frequency Crystal'),
(117, 'Guristas Rocket', 387, 'Rocket'),
(118, 'Sansha Rocket', 387, 'Rocket'),
(119, 'Guristas Light Missile', 384, 'Light Missile'),
(120, 'Sansha Light Missile', 384, 'Light Missile'),
(121, 'Guristas Heavy Missile', 385, 'Heavy Missile'),
(122, 'Sansha Heavy Missile', 385, 'Heavy Missile'),
(123, 'Guristas Heavy Assault Missile', 772, 'Assault Missile'),
(124, 'Sansha Heavy Assault Missile', 772, 'Assault Missile'),
(125, 'Guristas Cruise Missile', 386, 'Cruise Missile'),
(126, 'Sansha Cruise Missile', 386, 'Cruise Missile'),
(127, 'Guristas Torpedo', 89, 'Torpedo'),
(128, 'Sansha Torpedo', 89, 'Torpedo'),
# Rogue drone alloys section
(129, 'Low-grade alloys(High chance)', 355, 'Refinables'),
(130, 'Low-grade alloys(Low chance)', 355, 'Refinables'),
(131, 'Mid-grade alloys(High chance)', 355, 'Refinables'),
(132, 'Mid-grade alloys(Low chance)', 355, 'Refinables'),
(133, 'High-grade alloys(High chance)', 355, 'Refinables'),
(134, 'High-grade alloys(Low chance)', 355, 'Refinables');
